In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np


In [4]:
from sklearn.datasets import load_digits

In [5]:
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3,random_state=1)

In [22]:
log=LogisticRegression(solver='liblinear')
log.fit(x_train,y_train)
log.score(x_test,y_test)

0.9629629629629629

In [23]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9851851851851852

In [24]:
rm=RandomForestClassifier()
rm.fit(x_train,y_train)
rm.score(x_test,y_test)

0.9851851851851852

In [25]:
from sklearn.model_selection import cross_val_score


In [26]:
cross_val_score(LogisticRegression(solver='liblinear'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [44]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [28]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.93155259, 0.95659432, 0.93155259])

In [29]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=3)
np.average(scores1)

0.8614357262103507

In [30]:
score2=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=3)
np.average(score2)

0.9265442404006677

In [31]:
score3=cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=3)
np.average(score3)

0.9293266555370061

In [42]:
score4=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)
np.average(score4)

0.9354479688369505